### ISSUE TITLE
logical error in c programme to find area of a circle.

### ISSUE THREAD

**Issue by sarvendrasingh** [sarvendrasingh/LabCodes#1]
`/*
program to find the area of a cirle of given radius
*/
#include<stdio.h>
//#include<math.h>
int main()
{
	float r=0.0f, a=0.0f;
	char ch;
	do
	{
		printf("Enter the radius of circle to find its area:\n");
		scanf("%f", &r);
		a = 3.14159 * r * r ;
		printf("The area of the circle of radius %f is %.4f\n", r, a);
		printf("Do you wish to continue?\t [y/n]\n");
		scanf(" %c ", &ch);
	}while( ch == 'y' );
	if (ch == 'n')
	{
		printf("Goodbye\n");
	}
	else 
	{
		printf("Sorry! Wrong input.\n");
	}
	return 0;
}

/* the same file is uploaded on my repository with below link:
`https://github.com/sarvendrasingh/LabCodes/blob/master/area.c
*/

**Comment by sarvendrasingh** [comment]
![screenshot from 2018-11-21 01-30-50](https://user-images.githubusercontent.com/43023383/48799447-267f7a80-ed2d-11e8-97f4-d6f2eb6bd7d3.png)
even if i change my input,, it runs on the old input and asks new input after running it again...

**Comment by dbc2201** [comment]
Did the pull request fix the bug?

**Comment by sarvendrasingh** [comment]
yes sir.. thank you very much..
